cluster.name: es-TaoTuo
node.name: es04
node.master: true
node.data: false
bootstrap.memory_lock: true
network.host: 0.0.0.0
discovery.seed_hosts:
  - es01
cluster.initial_master_nodes:
  - es01
  - es04
http.cors.enabled: true
http.cors.allow-origin: "*"
xpack.monitoring.collection.enabled: true